title: Gustavo de Morais
description: Notes on Apache Flink, streaming SQL, and other engineering things.
theme: minima
minima:
  skin: classic
show_excerpts: true

author: Gustavo de Morais
email: gustavopguto@gmail.com
github_username: gustavodemorais
linkedin_username: gustavo-demorais

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
